# -*- coding: utf-8 -*-
"""why_numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PaXk-X18SdrecRqYoZK3Pz3Kpl5JCSI-
"""

!pip install numpy

import numpy as np

array = np.array([1,2,3,4,5])

print(type(array))

revenues = [2000,5000,3000,6500,7200,3100,2650,1900,3820,5120,4100]

import time

initial_time = time.time()
sum = 0

for i in revenues:
  sum += i
print(sum)
termination_time = time.time()
 
print("Execution Time: ",termination_time-initial_time)

array = np.array(revenues)
 
initial_time = time.time()
 
sum = array.sum()
print(sum)
termination_time = time.time()
 
print("Execution Time: ",termination_time-initial_time)

x = ['Ben',500,'Jake','Liz',6000]
print(x)

for i in x:
  print(type(i))

arrayx = np.array(x)
print(arrayx)

for i in arrayx:
  print(type(i))

array2  = np.array([[1, 2, 3], [4, 5, 6]])

print(array2)

array2.ndim

array2.shape

array2.size

